// <auto-generated />
namespace AcmeWebsite.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Mig_DB_LastName_Ajust : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mig_DB_LastName_Ajust));
        
        string IMigrationMetadata.Id
        {
            get { return "201704280654386_Mig_DB_LastName_Ajust"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
